const CACHE_NAME = 'pestovo-v1.87.0-fa6115bf';
const CDN_CACHE = 'pestovo-cdn-v1';
const OFFLINE_URL = 'offline.html';

// Stale-while-revalidate для immutable-ресурсов: отдаём из кэша мгновенно
// и обновляем в фоне. Подходит для шрифтов/иконок, у которых URL содержит версию.
function staleWhileRevalidate(request, cacheName) {
    return caches.open(cacheName).then(function(cache) {
        return cache.match(request).then(function(cached) {
            var network = fetch(request).then(function(response) {
                if (response && (response.ok || response.type === 'opaque')) {
                    cache.put(request, response.clone());
                }
                return response;
            }).catch(function() { return null; });
            return cached || network.then(function(r) { return r || new Response('', { status: 408 }); });
        });
    });
}

// BEGIN PRECACHE (auto-generated by tools/rev-assets.js — не править вручную; запуск: npm run assets)
const STATIC_ASSETS = [
    // Страницы
    './',
    'admin.html',
    'auth.html',
    'design-preview.html',
    'handicap.html',
    'hcp-badge-preview.html',
    'index.html',
    'leaderboard.html',
    'marker.html',
    'offline.html',
    'players.html',
    'qr-start.html',
    'scorer.html',
    'setup-round.html',
    'stats.html',
    'tournaments.html',

    // Стили и скрипты (?v= — hash содержимого, генерируется tools/rev-assets.js)
    'css/design-presets.css?v=77ff3916',
    'css/style.css?v=897b10b1',
    'css/tn-studio.css?v=257f9601',
    'css/tournament-redesign.css?v=6aa85f7a',
    'dist/livescoring-modules.js?v=8347afb4',
    'js/app.js?v=24b60a94',
    'js/auth.js?v=dabbb67a',
    'js/design-preview.js?v=adbbac01',
    'js/design-system.js?v=78b8d092',
    'js/firebase-config.js?v=57564a0d',
    'js/handicap.js?v=ad1e9c00',
    'js/leaderboard.js?v=da62402e',
    'js/live.js?v=761232e2',
    'js/marker.js?v=83370556',
    'js/players.js?v=70c37568',
    'js/protocol.js?v=adbd9834',
    'js/pwa.js?v=83430aef',
    'js/qr-start.js?v=0ac378b8',
    'js/round-setup.js?v=8bda9181',
    'js/score-write.js?v=6f39f00e',
    'js/scorer.js?v=d3ff6c12',
    'js/solo.js?v=de90bfb9',
    'js/stats.js?v=f351c5ac',
    'js/tn-scorecard.js?v=3ea4ebce',
    'js/tn-studio-core.js?v=084a748a',
    'js/tn-studio-public.js?v=db544445',
    'js/tournament-core.js?v=6fbba5de',
    'js/tournament-public.js?v=1932a4cb',
    'js/tournaments.js?v=0b3a013f',
    'js/utils.js?v=aeaff755',

    // Прочее
    'manifest.json',
    'img/icon-180.png',
    'img/icon-192.png',
    'img/icon-512.png',
    'img/logo.png',
];
// END PRECACHE

self.addEventListener('install', function(event) {
    event.waitUntil(
        caches.open(CACHE_NAME).then(function(cache) {
            // Один временно недоступный ресурс не должен ломать установку PWA целиком.
            return Promise.all(STATIC_ASSETS.map(function(url) {
                return cache.add(url).catch(function(error) {
                    console.warn('[SW] Cannot precache ' + url, error);
                });
            }));
        }).then(function() { return self.skipWaiting(); })
    );
});

self.addEventListener('activate', function(event) {
    event.waitUntil(
        caches.keys().then(function(names) {
            // Чистим всё, кроме основного кэша и CDN-кэша шрифтов/иконок.
            return Promise.all(names.filter(function(name) {
                return name !== CACHE_NAME && name !== CDN_CACHE;
            }).map(function(name) { return caches.delete(name); }));
        }).then(function() { return self.clients.claim(); })
    );
});

self.addEventListener('fetch', function(event) {
    if (event.request.method !== 'GET') return;

    var requestUrl = new URL(event.request.url);
    var isSameOrigin = requestUrl.origin === self.location.origin;

    // Шрифты Google и Font Awesome с cdnjs кэшируем, чтобы офлайн-PWA
    // не оставался без иконок и фирменного шрифта на поле без сети.
    var cdnHost = requestUrl.hostname;
    if (!isSameOrigin &&
        (cdnHost.indexOf('fonts.gstatic.com') !== -1 ||
         cdnHost.indexOf('fonts.googleapis.com') !== -1 ||
         cdnHost.indexOf('cdnjs.cloudflare.com') !== -1)) {
        event.respondWith(staleWhileRevalidate(event.request, CDN_CACHE));
        return;
    }

    // API и прокси всегда читаются из сети: кэшированные данные здесь опасны.
    if (!isSameOrigin || requestUrl.hostname.indexOf('firebaseio.com') !== -1 ||
        requestUrl.hostname.indexOf('googleapis.com') !== -1 ||
        requestUrl.hostname.indexOf('hcp.rusgolf.ru') !== -1 ||
        requestUrl.hostname.indexOf('r.jina.ai') !== -1 ||
        requestUrl.hostname.indexOf('allorigins') !== -1 ||
        requestUrl.hostname.indexOf('codetabs') !== -1 ||
        requestUrl.hostname.indexOf('corsproxy') !== -1) return;

    // Для страниц сначала сеть: после релиза пользователь сразу получает свежий HTML.
    if (event.request.mode === 'navigate' || event.request.destination === 'document') {
        event.respondWith(
            fetch(event.request).then(function(response) {
                if (response && response.ok) {
                    var copy = response.clone();
                    caches.open(CACHE_NAME).then(function(cache) { cache.put(event.request, copy); });
                }
                return response;
            }).catch(function() {
                return caches.match(event.request).then(function(cached) {
                    return cached || caches.match(OFFLINE_URL);
                });
            })
        );
        return;
    }

    // Статика открывается мгновенно из кэша и обновляется в фоне.
    event.respondWith(
        caches.match(event.request).then(function(cached) {
            var network = fetch(event.request).then(function(response) {
                if (response && response.ok) {
                    var copy = response.clone();
                    caches.open(CACHE_NAME).then(function(cache) { cache.put(event.request, copy); });
                }
                return response;
            });
            if (cached) {
                event.waitUntil(network.catch(function() {}));
                return cached;
            }
            return network.catch(function() { return new Response('', { status: 408 }); });
        })
    );
});

// ============================================
// ФОНОВЫЕ PUSH-УВЕДОМЛЕНИЯ (приложение закрыто)
// Платформа: Cloud Function onBroadcastCreated/onAlertCreated
// отправляет Web Push (VAPID) с JSON {title,body,tag,url}.
// ============================================
self.addEventListener('push', function(event) {
    var data = {};
    try { data = event.data ? event.data.json() : {}; } catch (e) {
        try { data = { body: event.data ? event.data.text() : '' }; } catch (e2) { data = {}; }
    }
    var title = data.title || 'Pestovo Live Scoring';
    var options = {
        body: data.body || '',
        icon: 'img/icon-192.png',
        badge: 'img/icon-192.png',
        vibrate: [200, 80, 200],
        tag: data.tag || 'pestovo-push',
        renotify: true,
        requireInteraction: !!data.requireInteraction,
        data: { url: data.url || 'index.html' }
    };
    event.waitUntil(self.registration.showNotification(title, options));
});

// Браузер может обновить push-подписку сам — переподписываемся с тем же
// VAPID-ключом и обновляем запись в базе через клиент, если он есть.
self.addEventListener('pushsubscriptionchange', function(event) {
    event.waitUntil(
        (async function() {
            try {
                var dbUrl = 'https://livescore-b77e4-default-rtdb.firebaseio.com/settings/vapid_public_key.json';
                var resp = await fetch(dbUrl, { cache: 'no-store' });
                var publicKey = await resp.json();
                if (!publicKey) return;
                var reg = await self.registration.pushManager.subscribe({
                    userVisibleOnly: true,
                    applicationServerKey: urlBase64ToUint8Array(publicKey)
                });
                // Клиент при следующем запуске сам перезапишет подписку;
                // здесь лишь гарантируем, что подписка существует.
                var clientsAll = await clients.matchAll({ includeUncontrolled: true });
                clientsAll.forEach(function(c) { try { c.postMessage({ type: 'pestovo-push-resubscribed' }); } catch (e) {} });
                return reg;
            } catch (e) {}
        })()
    );
});

function urlBase64ToUint8Array(base64String) {
    var padding = '='.repeat((4 - (base64String.length % 4)) % 4);
    var base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
    var raw = atob(base64);
    var out = new Uint8Array(raw.length);
    for (var i = 0; i < raw.length; ++i) out[i] = raw.charCodeAt(i);
    return out;
}

self.addEventListener('notificationclick', function(event) {
    event.notification.close();
    var rawTarget = (event.notification.data && event.notification.data.url) || 'index.html';
    var targetUrl = new URL(rawTarget, self.location.origin).href;
    if (new URL(targetUrl).origin !== self.location.origin) targetUrl = new URL('index.html', self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
            if (clientList.length) {
                var client = clientList[0];
                return client.focus().then(function() {
                    return 'navigate' in client ? client.navigate(targetUrl) : client;
                });
            }
            return clients.openWindow ? clients.openWindow(targetUrl) : undefined;
        })
    );
});
