#!/usr/bin/env node
'use strict';
/*
 * rev-assets.js — автоматические версии статики и precache-манифест Service Worker.
 *
 * Закрывает п.6 docs/CODE-REVIEW.md: «CACHE_NAME захардкожен, версии ассетов
 * проставляются вручную — забытая версия = пользователи на старом кэше».
 *
 * Что делает:
 *  1. Сканирует все корневые *.html на предмет локальных js/css
 *     (атрибуты src=/href=) и проставляет/обновляет ?v=<hash8>,
 *     где hash8 — первые 8 символов SHA-1 содержимого файла.
 *     Изменил файл → следующая сборка сама получит новый URL в HTML и SW.
 *  2. Пересобирает блок precache-манифеста в sw.js между маркерами
 *     BEGIN/END PRECACHE: все страницы + все найденные ассеты (с их ?v=)
 *     + manifest.json + img/* + docs/assistant-*.json.
 *  3. Выводит CACHE_NAME из версии сайта (index.html → .version-number)
 *     и хеша манифеста: 'pestovo-v<версия>-<hash8>'. Любое изменение
 *     ассетов меняет имя кэша → старый кэш гарантированно сбрасывается
 *     в activate().
 *
 * Режимы:
 *   node tools/rev-assets.js            — применить (переписать файлы)
 *   node tools/rev-assets.js --check    — только проверить (CI/тест):
 *                                         exit 1, если что-то устарело
 *
 * Проверки целостности (в обоих режимах):
 *   — каждая js/css-ссылка в HTML ведёт к существующему файлу
 *     (ловит опечатки в <script src=…>);
 *   — каждый URL манифеста существует на диске.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const CHECK = process.argv.includes('--check');

const BEGIN = '// BEGIN PRECACHE (auto-generated by tools/rev-assets.js — не править вручную; запуск: npm run assets)';
const END = '// END PRECACHE';

function fail(msg) { console.error('rev-assets: ' + msg); process.exit(1); }
function sha8(buf) { return crypto.createHash('sha1').update(buf).digest('hex').slice(0, 8); }
function readUtf8(p) { return fs.readFileSync(path.join(ROOT, p), 'utf8'); }
function exists(p) { return fs.existsSync(path.join(ROOT, p)); }

// ── 1. Сбор локальных js/css-ссылок из HTML ──────────────────────────────
const htmlFiles = fs.readdirSync(ROOT).filter(function (f) { return f.endsWith('.html'); }).sort();

const REF_RE = /(?:src|href)=("|')((?:js|css)\/[^"'?#]+)(?:\?v=[0-9a-zA-Z]+)?\1/g;

const refs = new Map(); // 'js/utils.js' -> Set<page>
let brokenRefs = 0;
for (const page of htmlFiles) {
    const html = readUtf8(page);
    REF_RE.lastIndex = 0;
    let m;
    while ((m = REF_RE.exec(html)) !== null) {
        const file = m[2];
        if (!exists(file)) {
            console.error('ОШИБКА: ' + page + ' ссылается на отсутствующий файл "' + file + '"');
            brokenRefs++;
            continue;
        }
        if (!refs.has(file)) refs.set(file, new Set());
        refs.get(file).add(page);
    }
}
if (brokenRefs) fail('битых ссылок в HTML: ' + brokenRefs);
if (!refs.size) fail('в HTML не найдено ни одной js/css-ссылки');

// ── 2. Хеши версий ────────────────────────────────────────────────────────
const versions = new Map(); // 'js/utils.js' -> 'hash8'
for (const file of refs.keys()) versions.set(file, sha8(fs.readFileSync(path.join(ROOT, file))));

// ── 3. Переписывание ?v= в HTML ───────────────────────────────────────────
const ATTR_RE = /((?:src|href)=("|'))((?:js|css)\/[^"'?#]+)(\?v=[0-9a-zA-Z]+)?(\2)/g;
const changedHtml = [];
for (const page of htmlFiles) {
    const html = readUtf8(page);
    const next = html.replace(ATTR_RE, function (all, pre, q, file, oldV, post) {
        const v = versions.get(file);
        if (!v) return all; // не собирали выше (битая ссылка уже зафэйлилась)
        return pre + file + '?v=' + v + post;
    });
    if (next !== html) {
        changedHtml.push(page);
        if (!CHECK) fs.writeFileSync(path.join(ROOT, page), next);
    }
}

// ── 4. Precache-манифест ──────────────────────────────────────────────────
const pages = ['./'].concat(htmlFiles);
const assets = Array.from(refs.keys()).sort().map(function (f) { return f + '?v=' + versions.get(f); });

const extras = [];
if (exists('manifest.json')) extras.push('manifest.json');
const imgDir = path.join(ROOT, 'img');
if (fs.existsSync(imgDir)) {
    fs.readdirSync(imgDir).sort().forEach(function (f) { extras.push('img/' + f); });
}
['docs/assistant-index.json', 'docs/assistant-sources.json'].forEach(function (f) {
    if (exists(f)) extras.push(f);
});

for (const url of [].concat(pages, assets, extras)) {
    if (!exists(url.split('?')[0])) fail('манифест ссылается на отсутствующий файл: ' + url);
}

const manifest = [].concat(pages, assets, extras);

// ── 5. CACHE_NAME = версия сайта + хеш манифеста ─────────────────────────
const verMatch = /class="version-number">([\d.]+)</.exec(readUtf8('index.html'));
if (!verMatch) fail('index.html: не найден <span class="version-number">…</span>');
const siteVersion = verMatch[1];
const cacheName = 'pestovo-v' + siteVersion + '-' + sha8(Buffer.from(manifest.join('\n'), 'utf8'));

// ── 6. Переписывание sw.js ────────────────────────────────────────────────
const swPath = path.join(ROOT, 'sw.js');
const sw = fs.readFileSync(swPath, 'utf8');

const cacheLineRe = /^const CACHE_NAME = '.*';$/m;
const newCacheLine = "const CACHE_NAME = '" + cacheName + "';";
if (!cacheLineRe.test(sw)) fail('sw.js: не найдена строка const CACHE_NAME = …;');

const swReplaced = sw.replace(cacheLineRe, newCacheLine);
const beginIdx = swReplaced.indexOf(BEGIN);
const endIdx = swReplaced.indexOf(END);
if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    fail('sw.js: не найдены маркеры ' + JSON.stringify(BEGIN.slice(0, 30) + '…') + ' / ' + END);
}

const lines = [];
lines.push(BEGIN);
lines.push('const STATIC_ASSETS = [');
lines.push('    // Страницы');
pages.forEach(function (u, i) { lines.push('    \'' + u + '\','); });
lines.push('');
lines.push('    // Стили и скрипты (?v= — hash содержимого, генерируется tools/rev-assets.js)');
assets.forEach(function (u) { lines.push('    \'' + u + '\','); });
lines.push('');
lines.push('    // Прочее');
extras.forEach(function (u) { lines.push('    \'' + u + '\','); });
lines.push('];');
lines.push(END);
const newBlock = lines.join('\n');

const nextSw = swReplaced.slice(0, beginIdx) + newBlock + swReplaced.slice(endIdx + END.length);

const swChanged = nextSw !== sw;
if (swChanged && !CHECK) fs.writeFileSync(swPath, nextSw);

// ── Отчёт ─────────────────────────────────────────────────────────────────
const summary = 'ассетов: ' + manifest.length + ' (страниц: ' + pages.length +
    ', js+css: ' + assets.length + ', прочее: ' + extras.length + '), CACHE_NAME: ' + cacheName;

if (CHECK) {
    if (changedHtml.length || swChanged) {
        console.error('rev-assets --check: устарело. HTML: ' +
            (changedHtml.join(', ') || '—') + '; sw.js: ' + (swChanged ? 'манифест/CACHE_NAME' : 'актуален'));
        console.error('Запустите: npm run assets');
        process.exit(1);
    }
    console.log('rev-assets --check: OK. ' + summary);
} else {
    console.log('rev-assets: обновлено HTML: ' + (changedHtml.length ? changedHtml.join(', ') : 'нет') +
        '; sw.js: ' + (swChanged ? 'да' : 'нет') + '. ' + summary);
}
